name: use herald

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  herald:
    name: apply herald rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: apply herald rules
        id: herald
        uses: gagoar/use-herald-action@v2.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: herald_rules/*.json
          DEBUG: '*'

      - name: Store response payload to file
        run: echo '${{ fromJSON(steps.herald.outputs.appliedRules) }}'
